backend:
  name: github
  repo: sammansoori/corpokart-site
  branch: main
  auth_scope: repo
  base_url: https://netlify-cms-oauth.netlify.app

media_folder: "static/uploads"    # Jahaan CMS images save karega
public_folder: "/uploads"          # Browser mein ye folder se images serve hongi

collections:
  - name: "products"
    label: "Products"
    folder: "products"            # products folder mein content files hongi
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
