backend:
  name: github
  repo: sammansoori/corpokart-site  # Apna github username/repo yahan daalo
  branch: main                       # Jis branch pe kaam kar rahe ho

media_folder: "static/uploads"       # Jahaan tum media files upload karna chahte ho
public_folder: "/uploads"             # Ye browser me access ka path hoga

collections:
  - name: "products"
    label: "Products"
    folder: "products"               # Products ka folder tumhare root me hai
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "content"
    label: "Content"
    folder: "content"                # Content folder bhi root me hai
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

# Media library agar chahiye to simple builtin rakh sakte ho:
media_library:
  name: uploadcare
  config:
    publicKey: "your_uploadcare_public_key"   # Agar uploadcare use nahi karna to isko hata do ya comment karo

