backend:
  name: github
  repo: sammansoori/corpokart-site
  branch: main
  auth_scope: repo           # Ye permissions specify karta hai
  base_url: https://netlify-cms-oauth.netlify.app  # Public OAuth proxy (recommended for beginners)
  app_id: Ov23li5XO37KKstYSdc1     # Yahan GitHub se mila Client ID daalo
