backend:
  name: github
  repo: sammansoori/corpokart-site
  branch: main

media_folder: "products"    # Tumhara wo folder jisme product files rakhe ho
public_folder: "/products"  # URL me access ke liye

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
