backend:
  name: github
  repo: sammansoori/corpokart-site
  branch: main
  auth_scope: repo
  base_url: https://netlify-cms-oauth.netlify.app
  # yahan client_id add karna hai (agar support kare)
  client_id: Ov23li5XO37KKstYSdc1
  # client_secret normally config.yml me nahi dalte (security reasons)
